##
## This file was generated by Google::ProtocolBuffers (0.08)
## on Tue Apr 19 12:49:06 2011
##      
use strict;
use warnings;
use Google::ProtocolBuffers;
{       
    unless (AppsRequest::ViewType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'AppsRequest::ViewType',
            [
               ['ALL', 0],
               ['FREE', 1],
               ['PAID', 2],

            ]
        );
    }
    
    unless (GetImageRequest::AppImageUsage->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'GetImageRequest::AppImageUsage',
            [
               ['ICON', 0],
               ['SCREENSHOT', 1],
               ['SCREENSHOT_THUMBNAIL', 2],
               ['PROMO_BADGE', 3],
               ['BILING_ICON', 4],

            ]
        );
    }
    
    unless (AppType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'AppType',
            [
               ['NONE', 0],
               ['APPLICATION', 1],
               ['RINGTONE', 2],
               ['WALLPAPER', 3],
               ['GAME', 4],

            ]
        );
    }
    
    unless (AppsRequest::OrderType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'AppsRequest::OrderType',
            [
               ['NONE', 0],
               ['POPULAR', 1],
               ['NEWEST', 2],
               ['FEATURED', 3],

            ]
        );
    }
    
    unless (SubCategoriesResponse->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'SubCategoriesResponse',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'Category', 
                    'category', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'subCategoryDisplay', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'subCategoryId', 3, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (CommentsResponse->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CommentsResponse',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'Comment', 
                    'comments', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'entriesCount', 2, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (GetImageRequest->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'GetImageRequest',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'appId', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'GetImageRequest::AppImageUsage', 
                    'imageUsage', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'imageId', 4, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Request::RequestGroup->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_group(
            'Request::RequestGroup',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'AppsRequest', 
                    'appsRequest', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CommentsRequest', 
                    'commentsRequest', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'GetAppRequest', 
                    'getAppRequest', 10, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'GetImageRequest', 
                    'imageRequest', 11, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'SubCategoriesRequest', 
                    'subCategoriesRequest', 14, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CategoriesRequest', 
                    'categoriesRequest', 21, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (ResponseContext->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'ResponseContext',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'result', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'unknown1', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'unknown2', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'unknown3', 4, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Response::ResponseGroup->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_group(
            'Response::ResponseGroup',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'ResponseContext', 
                    'context', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'AppsResponse', 
                    'appsResponse', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CommentsResponse', 
                    'commentsResponse', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'GetAppResponse', 
                    'getAppResponse', 9, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'GetImageResponse', 
                    'imageResponse', 10, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'SubCategoriesResponse', 
                    'subCategoriesResponse', 13, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CategoriesResponse', 
                    'categoriesResponse', 20, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (App->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'App',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'id', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'title', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'AppType', 
                    'appType', 3, 0
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'creator', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'version', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'price', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'rating', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'ratingsCount', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'App::ExtendedInfo', 
                    'ExtendedInfo', 12, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'creatorId', 22, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'packageName', 24, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'versionCode', 25, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'priceCurrency', 32, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'priceMicros', 33, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Request->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Request',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'RequestContext', 
                    'context', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'Request::RequestGroup', 
                    'RequestGroup', 2, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (AppsRequest->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'AppsRequest',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'AppType', 
                    'appType', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'query', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'categoryId', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'appId', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_BOOL(), 
                    'withExtendedInfo', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'AppsRequest::OrderType', 
                    'orderType', 7, 0
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_UINT64(), 
                    'startIndex', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'entriesCount', 9, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'AppsRequest::ViewType', 
                    'viewType', 10, 0
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (GetAppRequest->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'GetAppRequest',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'appId', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (RequestContext->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'RequestContext',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'authSubToken', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'unknown1', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'version', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'androidId', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'deviceAndSdkVersion', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'userLanguage', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'userCountry', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'operatorAlpha', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'simOperatorAlpha', 9, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'operatorNumeric', 10, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'simOperatorNumeric', 11, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'clientId', 12, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'loggingId', 13, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (CategoriesResponse->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CategoriesResponse',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'Category', 
                    'categories', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Comment->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Comment',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'text', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'rating', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'authorName', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_UINT64(), 
                    'creationTime', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'authorId', 5, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (CategoriesRequest->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CategoriesRequest',
            [

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Response->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Response',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'Response::ResponseGroup', 
                    'ResponseGroup', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (CommentsRequest->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CommentsRequest',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'appId', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'startIndex', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'entriesCount', 3, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (GetAppResponse->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'GetAppResponse',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'GetAppResponse::AppDetail', 
                    'AppDetail', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (SubCategoriesRequest->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'SubCategoriesRequest',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'AppType', 
                    'appType', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (AppsResponse->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'AppsResponse',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'App', 
                    'app', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'entriesCount', 2, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (App::ExtendedInfo->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_group(
            'App::ExtendedInfo',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'description', 13, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'downloadsCount', 14, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'permissionId', 15, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'installSize', 16, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'packageName', 17, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'category', 18, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'contactEmail', 20, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'downloadsCountText', 23, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'contactPhone', 26, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'contactWebsite', 27, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'screenshotsCount', 30, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'promoText', 31, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'recentChanges', 38, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'promotionalVideo', 43, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (GetAppResponse::AppDetail->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_group(
            'GetAppResponse::AppDetail',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'assetId', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'assetBlobURL', 6, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Category->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Category',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'appType', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'categoryId', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'title', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'subtitle', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'Category', 
                    'subCategories', 8, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (GetImageResponse->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'GetImageResponse',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_BYTES(), 
                    'imageData', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

}
1;
